CC=gcc
CFLAGS=-g -Wall -D_FILE_OFFSET_BITS=64
LDFLAGS=-lfuse

OBJ=tfs.o block.o

%.o: %.c
	$(CC) -c $(CFLAGS) -lm $< -o $@

tfs: $(OBJ)
	$(CC) $(OBJ) $(LDFLAGS) -lm -o tfs

.PHONY: clean
clean:
	rm -f *.o tfs

